<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use App\Models\Tag;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function createRecipe($recipe, $ingredients, $tags): void
    {
        $recipe_id = DB::table('recipes')->insertGetId($recipe);

        foreach ($ingredients as $ingredient) {
            $ingredient_id = Ingredient::firstOrCreate($ingredient)->id;

            DB::table('ingredient_recipe')->insert([
                'recipe_id' => $recipe_id,
                'ingredient_id' => $ingredient_id,
            ]);
        }

        foreach ($tags as $tag) {
            $tag_id = Tag::firstOrCreate($tag)->id;

            DB::table('recipe_tag')->insert([
                'recipe_id' => $recipe_id,
                'tag_id' => $tag_id,
            ]);
        }
    }

    public function run(): void
    {
        $current_recipe = [
            'name' => 'Harissa Chicken on Quinoa',
            'headline' => 'This dish produces 50% less CO2e from ingredients than an average HelloFresh recipe',
            'preptime' => '25',
            'instructions' => 'Create a flavorful Harissa Chicken on Quinoa with Green Olives by marinating and searing the chicken. Cook quinoa separately, mix with green olives, and plate the dish for a visually appealing meal.',
            'image' => 'https://img.hellofresh.com/q_auto/recipes/image/HF_Y23_R37_W44_DE_R4819-1_Main_low-661e95c9.jpg',
            'calories' => 606,
            'carbs' => 52.54,
            'fat' => 30,
            'protein' => 38.4,
            'sugar' => 5.6,
            'sustainability_rating' => 0.85,

        ];

        $ingredients = [[
            'name' => 'Chicken Breast',
            'is_vegan' => false,
            'is_vegetarian' => false,
        ], [
            'name' => 'Quinoa',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Green Olives',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Harissa Spice Blend',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Garlic',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Lemon',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Sour Cream',
            'is_vegan' => false,
            'is_vegetarian' => true,
        ], [
            'name' => 'Olive Oil',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Salt',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Pepper',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Water',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Sugar',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Vegetable Stock Concentrate',
            'is_vegan' => true,
            'is_vegetarian' => true,
        ], [
            'name' => 'Butter',
            'is_vegan' => false,
            'is_vegetarian' => true,
        ]];

        $tags = [['name' => 'Low Calorie'],
            ['name' => 'High Protein']];
        $this->createRecipe($current_recipe, $ingredients, $tags);
        $this->createRecipe(['name' => 'Grilled Salmon with Lemon Dill Sauce', 'headline' => 'A zesty and flavorful salmon dish', 'preptime' => '30', 'instructions' => 'Grill salmon fillets and top with a tangy lemon dill sauce.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/65235c856c96c01e5b4700ed-a5457b80.jpeg', 'calories' => 450, 'carbs' => 12.8, 'fat' => 28, 'protein' => 36.5, 'sugar' => 2.5, 'sustainability_rating' => 0.75], [['name' => 'Salmon', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Lemon', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Dill', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Low Carb'], ['name' => 'High Protein']]);
        $this->createRecipe(['name' => 'Vegetarian Lentil Stew', 'headline' => 'A hearty and nutritious plant-based stew', 'preptime' => '40', 'instructions' => 'Simmer lentils, vegetables, and spices to create a delicious and filling vegetarian stew.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/64e2c08edd7d57f2ca82c08c-2bbec2cc.jpeg', 'calories' => 320, 'carbs' => 58.2, 'fat' => 1.8, 'protein' => 18.5, 'sugar' => 6.4, 'sustainability_rating' => 0.90], [['name' => 'Lentils', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Carrots', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Tomatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Vegetable Broth', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cumin', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Paprika', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bay Leaves', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'High Fiber']]);
        $this->createRecipe(['name' => 'Spaghetti Bolognese', 'headline' => 'Classic Italian pasta dish with a rich meat sauce', 'preptime' => '35', 'instructions' => 'Prepare a savory meat sauce with tomatoes, ground beef, and herbs. Serve over cooked spaghetti.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/klassische-pasta-bolognese-mit-rinderhack-bbacf739.jpg', 'calories' => 580, 'carbs' => 75.5, 'fat' => 22, 'protein' => 26, 'sugar' => 9.2, 'sustainability_rating' => 0.80], [['name' => 'Spaghetti', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Ground Beef', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Tomato Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Oregano', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Basil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Parmesan Cheese', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein']]);
        $this->createRecipe(['name' => 'Thai Red Curry with Tofu', 'headline' => 'A flavorful and spicy Thai-inspired curry', 'preptime' => '45', 'instructions' => 'Simmer tofu, vegetables, and Thai red curry paste in coconut milk. Serve over rice.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/thai-red-tofu-veggie-curry-728eb3e7.jpg', 'calories' => 420, 'carbs' => 30.5, 'fat' => 32, 'protein' => 12.8, 'sugar' => 5.2, 'sustainability_rating' => 0.85], [['name' => 'Tofu', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Red Curry Paste', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Coconut Milk', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bell Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Zucchini', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Carrots', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Basil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Soy Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Brown Sugar', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Lime', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Spicy']]);
        $this->createRecipe(['name' => 'Mushroom Risotto', 'headline' => 'Creamy and comforting Italian rice dish', 'preptime' => '50', 'instructions' => 'Sauté mushrooms, onions, and Arborio rice. Slowly add broth and Parmesan cheese to create a creamy risotto.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/5332347bff604d567f8b4574.jpg', 'calories' => 480, 'carbs' => 60.2, 'fat' => 18.5, 'protein' => 14.8, 'sugar' => 3.5, 'sustainability_rating' => 0.88], [['name' => 'Arborio Rice', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Mushrooms', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Vegetable Broth', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Parmesan Cheese', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'White Wine', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Butter', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Comfort Food']]);
        $this->createRecipe(['name' => 'Cajun Shrimp Pasta', 'headline' => 'A spicy and flavorful pasta with Cajun-seasoned shrimp', 'preptime' => '40', 'instructions' => 'Sauté shrimp with Cajun seasoning, garlic, and bell peppers. Toss with pasta and a creamy Alfredo sauce.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/6549b36bab5441ef936d8205-4ce975d5.jpeg', 'calories' => 550, 'carbs' => 45.8, 'fat' => 24, 'protein' => 38.5, 'sugar' => 3.8, 'sustainability_rating' => 0.82], [['name' => 'Shrimp', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Penne Pasta', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cajun Seasoning', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bell Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Heavy Cream', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Parmesan Cheese', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Butter', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Spicy']]);
        $this->createRecipe(['name' => 'Caprese Salad', 'headline' => 'A simple and refreshing Italian salad', 'preptime' => '15', 'instructions' => 'Layer fresh tomatoes, mozzarella, and basil. Drizzle with balsamic glaze and olive oil.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/552f366c6ced6e9b3c8b456f.jpg', 'calories' => 280, 'carbs' => 7.5, 'fat' => 22, 'protein' => 14.2, 'sugar' => 4.8, 'sustainability_rating' => 0.92], [['name' => 'Tomatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Mozzarella', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Basil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Balsamic Glaze', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian']]);
        $this->createRecipe(['name' => 'Chicken Caesar Salad', 'headline' => 'A classic Caesar salad with grilled chicken', 'preptime' => '30', 'instructions' => 'Grill chicken, toss with crisp romaine lettuce, croutons, and Caesar dressing.', 'image' => 'https://img.hellofresh.com/w_256,q_auto,f_auto,c_fill,fl_lossy/hellofresh_s3/image/64a7acb60c1283a508a6087a-51a66ece.jpeg', 'calories' => 420, 'carbs' => 18.2, 'fat' => 28, 'protein' => 28.5, 'sugar' => 3.2, 'sustainability_rating' => 0.78], [['name' => 'Chicken Breast', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Romaine Lettuce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Croutons', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Parmesan Cheese', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Caesar Dressing', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein']]);
        $this->createRecipe(['name' => 'Beef and Broccoli Stir-Fry', 'headline' => 'Quick and flavorful Asian-inspired stir-fry', 'preptime' => '25', 'instructions' => 'Stir-fry thinly sliced beef with broccoli in a savory soy-based sauce. Serve over rice.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/65234540e4436936d49a451a-0b500a48.jpeg', 'calories' => 480, 'carbs' => 35.8, 'fat' => 22, 'protein' => 36.2, 'sugar' => 6.5, 'sustainability_rating' => 0.80], [['name' => 'Beef Sirloin', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Broccoli', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Soy Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Ginger', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Sesame Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Rice', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Quick and Easy']]);
        $this->createRecipe(['name' => 'Vegetable Fajitas', 'headline' => 'A colorful and veggie-packed Tex-Mex dish', 'preptime' => '30', 'instructions' => 'Sauté bell peppers, onions, and mushrooms. Serve with tortillas, guacamole, and salsa.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/55496be46ced6ea6178b4568.jpg', 'calories' => 320, 'carbs' => 45.2, 'fat' => 14.5, 'protein' => 7.8, 'sugar' => 9.8, 'sustainability_rating' => 0.85], [['name' => 'Bell Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Mushrooms', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Tortillas', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Guacamole', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salsa', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cumin', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Chili Powder', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Tex-Mex']]);
        $this->createRecipe(['name' => 'Miso Glazed Salmon', 'headline' => 'A sweet and savory glazed salmon dish', 'preptime' => '35', 'instructions' => 'Brush salmon fillets with miso glaze and bake until golden. Serve with steamed vegetables.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/miso-glazed-salmon-a9f8ef66.jpg', 'calories' => 380, 'carbs' => 15.5, 'fat' => 24, 'protein' => 26.5, 'sugar' => 8.2, 'sustainability_rating' => 0.78], [['name' => 'Salmon', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Miso Paste', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Soy Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Maple Syrup', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Ginger', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Broccoli', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Carrots', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Snap Peas', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Sweet and Savory']]);
        $this->createRecipe(['name' => 'Quinoa and Black Bean Bowl', 'headline' => 'A protein-packed and nutritious grain bowl', 'preptime' => '40', 'instructions' => 'Combine cooked quinoa, black beans, corn, and avocado. Drizzle with lime vinaigrette.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/570ef4d2fd2cb9ea038b4567.jpg', 'calories' => 420, 'carbs' => 55.2, 'fat' => 16, 'protein' => 18.8, 'sugar' => 4.5, 'sustainability_rating' => 0.85], [['name' => 'Quinoa', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Black Beans', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Corn', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Avocado', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Tomatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Lime', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cilantro', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cumin', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'High Fiber']]);
        $this->createRecipe(['name' => 'Teriyaki Chicken Skewers', 'headline' => 'Sweet and savory grilled chicken skewers', 'preptime' => '30', 'instructions' => 'Marinate chicken in teriyaki sauce, thread onto skewers, and grill. Serve with rice.', 'image' => 'https://img.hellofresh.com/w_256,q_auto,f_auto,c_fill,fl_lossy/hellofresh_s3/image/teriyaki-chicken-noodles-with-veggies-lime-87e593aa.jpg', 'calories' => 480, 'carbs' => 35.5, 'fat' => 22.5, 'protein' => 28.2, 'sugar' => 12.8, 'sustainability_rating' => 0.82], [['name' => 'Chicken Thighs', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Teriyaki Sauce', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Bell Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pineapple', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Soy Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Ginger', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Rice', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Grilled']]);
        $this->createRecipe(['name' => 'Pesto Pasta with Cherry Tomatoes', 'headline' => 'A vibrant and herby pasta dish', 'preptime' => '25', 'instructions' => 'Toss cooked pasta with basil pesto and cherry tomatoes. Garnish with Parmesan.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/quick-pesto-cherry-tomato-pasta-78ecd1fb.jpg', 'calories' => 420, 'carbs' => 50.8, 'fat' => 20, 'protein' => 12.5, 'sugar' => 3.2, 'sustainability_rating' => 0.85], [['name' => 'Penne Pasta', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Basil Pesto', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cherry Tomatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Parmesan Cheese', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian']]);
        $this->createRecipe(['name' => 'Honey Mustard Glazed Chicken', 'headline' => 'A sweet and tangy glazed chicken dish', 'preptime' => '35', 'instructions' => 'Brush chicken breasts with honey mustard glaze and bake until golden. Serve with roasted vegetables.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/57172087f8b25e6f628b4568.jpg', 'calories' => 380, 'carbs' => 28.5, 'fat' => 18, 'protein' => 26.2, 'sugar' => 14.5, 'sustainability_rating' => 0.80], [['name' => 'Chicken Breasts', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Dijon Mustard', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Honey', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Rosemary', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Carrots', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Potatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Sweet and Savory']]);
        $this->createRecipe(['name' => 'Shrimp and Avocado Salad', 'headline' => 'A light and refreshing seafood salad', 'preptime' => '20', 'instructions' => 'Combine cooked shrimp, avocado, and mixed greens. Dress with lemon vinaigrette.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/crispy-chorizo-avocado-salad-bdc2efb4.jpg', 'calories' => 320, 'carbs' => 20.2, 'fat' => 22, 'protein' => 18.8, 'sugar' => 5.5, 'sustainability_rating' => 0.85], [['name' => 'Shrimp', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Avocado', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Mixed Greens', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Lemon', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Dijon Mustard', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Honey', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Seafood']]);
        $this->createRecipe(['name' => 'Mediterranean Quinoa Salad', 'headline' => 'A fresh and vibrant salad with Mediterranean flavors', 'preptime' => '30', 'instructions' => 'Combine cooked quinoa, cherry tomatoes, cucumber, feta, and olives. Dress with olive oil and lemon juice.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/warm-lentil-quinoa-salad-cb7b11ed.jpg', 'calories' => 350, 'carbs' => 40.8, 'fat' => 16.5, 'protein' => 12.2, 'sugar' => 3.8, 'sustainability_rating' => 0.88], [['name' => 'Quinoa', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cherry Tomatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cucumber', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Feta Cheese', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Kalamata Olives', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Lemon', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Oregano', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Mediterranean']]);
        $this->createRecipe(['name' => 'Stuffed Bell Peppers', 'headline' => 'A hearty and flavorful stuffed peppers dish', 'preptime' => '45', 'instructions' => 'Stuff bell peppers with a mixture of ground turkey, quinoa, black beans, and spices. Bake until tender.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/5252b1b6301bbf46038b4740.jpg', 'calories' => 420, 'carbs' => 35.5, 'fat' => 22, 'protein' => 26.8, 'sugar' => 8.2, 'sustainability_rating' => 0.82], [['name' => 'Bell Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Ground Turkey', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Quinoa', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Black Beans', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Tomato Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cumin', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Chili Powder', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Hearty']]);
        $this->createRecipe(['name' => 'Sauerbraten', 'headline' => 'Classic German pot roast marinated in a sweet and tangy sauce', 'preptime' => '120', 'instructions' => 'Marinate beef in a mixture of vinegar, water, and spices for several days. Slow-cook with onions until tender. Serve with red cabbage and potato dumplings.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/klassisches-putenbrustgulasch-470dffa8.jpg', 'calories' => 450, 'carbs' => 30.5, 'fat' => 24.8, 'protein' => 28.2, 'sugar' => 10.2, 'sustainability_rating' => 0.75], [['name' => 'Beef Roast', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Red Wine Vinegar', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bay Leaves', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Gingerbread Cookies', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Potato Dumplings', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Red Cabbage', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Potatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Traditional']]);
        $this->createRecipe(['name' => 'Kartoffelsalat', 'headline' => 'German-style potato salad with a tangy mustard dressing', 'preptime' => '40', 'instructions' => 'Boil potatoes, slice, and mix with a dressing of mustard, vinegar, and vegetable broth. Garnish with chives.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/53a19be5ff604d46188b456a.jpg', 'calories' => 220, 'carbs' => 38.2, 'fat' => 5.5, 'protein' => 3.5, 'sugar' => 4.8, 'sustainability_rating' => 0.80], [['name' => 'Potatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Mustard', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Vegetable Broth', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Vinegar', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Chives', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Sugar', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Traditional']]);
        $this->createRecipe(['name' => 'Wiener Schnitzel', 'headline' => 'A classic Viennese dish of breaded and fried veal cutlets', 'preptime' => '35', 'instructions' => 'Pound veal cutlets, coat with flour, dip in beaten eggs, and bread crumbs. Fry until golden brown. Serve with lemon wedges and parsley.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/schnitzel-mit-ofenkartoffeln-b293dcd1.jpg', 'calories' => 380, 'carbs' => 15.8, 'fat' => 22.2, 'protein' => 28.5, 'sugar' => 2.2, 'sustainability_rating' => 0.75], [['name' => 'Veal Cutlets', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Flour', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Eggs', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Breadcrumbs', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Lemon', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Parsley', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Potatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Butter', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Traditional']]);
        $this->createRecipe(['name' => 'Bratwurst with Sauerkraut', 'headline' => 'Grilled German sausages served with fermented cabbage', 'preptime' => '25', 'instructions' => 'Grill bratwurst sausages until cooked through. Serve with sauerkraut, mustard, and freshly baked pretzels.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/leckere-bratwurst-mit-brokkoli-thermomix-5c1a2eaf.jpg', 'calories' => 320, 'carbs' => 18.5, 'fat' => 26.2, 'protein' => 12.8, 'sugar' => 3.2, 'sustainability_rating' => 0.78], [['name' => 'Bratwurst Sausages', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Sauerkraut', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Mustard', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pretzels', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Beer', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Traditional'], ['name' => 'Grilled']]);
        $this->createRecipe(['name' => 'Coq au Vin', 'headline' => 'Classic French chicken stew in red wine', 'preptime' => '120', 'instructions' => 'Marinate chicken in red wine, cognac, and herbs. Sauté with bacon, mushrooms, and onions. Braise until chicken is tender. Serve over mashed potatoes or crusty bread.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/hahnchen-a-la-coq-au-vin-53fd0d14.jpg', 'calories' => 420, 'carbs' => 12.5, 'fat' => 28.2, 'protein' => 32.5, 'sugar' => 3.8, 'sustainability_rating' => 0.82], [['name' => 'Chicken', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Red Wine', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cognac', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bacon', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Mushrooms', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Carrots', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Thyme', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bay Leaves', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Flour', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Traditional']]);
        $this->createRecipe(['name' => 'Ratatouille', 'headline' => 'Vegetarian French Provençal stewed vegetable dish', 'preptime' => '50', 'instructions' => 'Layer thinly sliced eggplant, zucchini, and bell peppers in a baking dish. Top with tomato sauce and herbs. Bake until vegetables are tender. Serve with crusty bread.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/rauchiges-ratatouille-mit-ziegenkase-n-d1ba6ba6.jpg', 'calories' => 180, 'carbs' => 22.8, 'fat' => 9.5, 'protein' => 5.5, 'sugar' => 10.2, 'sustainability_rating' => 0.85], [['name' => 'Eggplant', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Zucchini', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bell Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Tomato Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Herbes de Provence', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Mediterranean']]);
        $this->createRecipe(['name' => 'Pad Thai', 'headline' => 'Thai stir-fried noodles with shrimp and tamarind sauce', 'preptime' => '30', 'instructions' => 'Stir-fry rice noodles with shrimp, tofu, bean sprouts, and green onions in a tamarind-based sauce. Garnish with peanuts and lime.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/thai-nudel-suppe-mit-rinderhack-75550b66.jpg', 'calories' => 360, 'carbs' => 45.2, 'fat' => 12.8, 'protein' => 18.5, 'sugar' => 6.2, 'sustainability_rating' => 0.86], [['name' => 'Rice Noodles', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Shrimp', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Tofu', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bean Sprouts', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Green Onions', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Tamarind Paste', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Peanuts', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Lime', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Soy Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Sugar', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Chili Flakes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Asian']]);
        $this->createRecipe(['name' => 'Tom Kha Gai', 'headline' => 'Thai coconut soup with chicken and mushrooms', 'preptime' => '30', 'instructions' => 'Simmer chicken, mushrooms, and lemongrass in a coconut milk broth. Season with fish sauce and lime juice. Garnish with cilantro and chili flakes.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/tom-kha-gai-mit-hahnchen-5c7a2553.jpg', 'calories' => 320, 'carbs' => 15.5, 'fat' => 22.2, 'protein' => 18.8, 'sugar' => 3.2, 'sustainability_rating' => 0.82], [['name' => 'Chicken Breast', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Mushrooms', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Coconut Milk', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Lemongrass', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Fish Sauce', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Lime', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cilantro', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Chili Flakes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Asian']]);
        $this->createRecipe(['name' => 'Quiche Lorraine', 'headline' => 'Savory pie with bacon, cheese, and a creamy egg filling', 'preptime' => '45', 'instructions' => 'Line a pie crust with bacon and pour over a mixture of eggs, cream, and cheese. Bake until set. Serve warm or at room temperature.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/54588b98ff604d48188b456b.jpg', 'calories' => 320, 'carbs' => 22.5, 'fat' => 22.8, 'protein' => 9.5, 'sugar' => 2.8, 'sustainability_rating' => 0.85], [['name' => 'Pie Crust', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Bacon', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Eggs', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Heavy Cream', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Gruyere Cheese', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Nutmeg', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Comfort Food']]);
        $this->createRecipe(['name' => 'Goulash', 'headline' => 'Hungarian beef stew with paprika and bell peppers', 'preptime' => '60', 'instructions' => 'Sauté beef with onions, garlic, and paprika. Add bell peppers, tomatoes, and beef broth. Simmer until beef is tender. Serve with egg noodles.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/5450e588ff604d50aa8b456c.jpg', 'calories' => 420, 'carbs' => 32.5, 'fat' => 22.2, 'protein' => 28.2, 'sugar' => 6.5, 'sustainability_rating' => 0.80], [['name' => 'Beef Stew Meat', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Paprika', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bell Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Tomatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Beef Broth', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Egg Noodles', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'European']]);
        $this->createRecipe(['name' => 'Jollof Rice', 'headline' => 'West African one-pot rice dish with tomatoes and spices', 'preptime' => '60', 'instructions' => 'Sauté onions, tomatoes, and bell peppers. Add rice, broth, and spices. Simmer until rice is cooked. Serve with grilled chicken or fish.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/jollof-afrikanischer-reistopf-mit-veganen-frikadellen-8e33cf16.jpg', 'calories' => 320, 'carbs' => 58.2, 'fat' => 8.5, 'protein' => 6.8, 'sugar' => 6.2, 'sustainability_rating' => 0.85], [['name' => 'Rice', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Tomatoes', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bell Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Vegetable Broth', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Thyme', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Bay Leaves', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cayenne Pepper', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Chicken or Fish', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Fiber'], ['name' => 'African']]);
        $this->createRecipe(['name' => 'California Roll', 'headline' => 'Japanese-American sushi roll with crab, avocado, and cucumber', 'preptime' => '50', 'instructions' => 'Prepare sushi rice, place on nori sheets, add crab, avocado, and cucumber. Roll and slice into bite-sized pieces. Serve with soy sauce and pickled ginger.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/5435164cff604dee2d8b456a.jpg', 'calories' => 220, 'carbs' => 45.2, 'fat' => 5.5, 'protein' => 8.8, 'sugar' => 4.2, 'sustainability_rating' => 0.90], [['name' => 'Sushi Rice', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Imitation Crab', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Avocado', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cucumber', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Nori Sheets', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Soy Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pickled Ginger', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Japanese']]);
        $this->createRecipe(['name' => 'Chicken Mole', 'headline' => 'Mexican sauce made with chocolate, chili, and spices', 'preptime' => '80', 'instructions' => 'Sear chicken, blend chili peppers, chocolate, and spices. Simmer sauce with chicken until cooked. Serve with rice or tortillas.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/645d96cb247002d589010010-c753a8c2.jpg', 'calories' => 380, 'carbs' => 25.5, 'fat' => 22.8, 'protein' => 28.2, 'sugar' => 4.8, 'sustainability_rating' => 0.86], [['name' => 'Chicken', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Dried Chili Peppers', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Chocolate', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Onion', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Garlic', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Almonds', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Sesame Seeds', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cinnamon', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Cumin', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Chicken Broth', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Rice or Tortillas', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'High Protein'], ['name' => 'Mexican']]);
        $this->createRecipe(['name' => 'Kimchi Fried Rice', 'headline' => 'Korean fried rice with kimchi and vegetables', 'preptime' => '30', 'instructions' => 'Sauté kimchi, vegetables, and rice with soy sauce and sesame oil. Top with a fried egg. Garnish with green onions.', 'image' => 'https://img.hellofresh.com/c_fit,f_auto,fl_lossy,h_1100,q_30,w_2600/hellofresh_s3/image/HF_Y23_R13_W35_UK_QR15742-4_Main__2low-bfaddcab.jpg', 'calories' => 280, 'carbs' => 48.2, 'fat' => 8.5, 'protein' => 6.5, 'sugar' => 3.2, 'sustainability_rating' => 0.88], [['name' => 'Kimchi', 'is_vegan' => false, 'is_vegetarian' => false], ['name' => 'Rice', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Carrots', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Peas', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Soy Sauce', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Sesame Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Egg', 'is_vegan' => false, 'is_vegetarian' => true], ['name' => 'Green Onions', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Olive Oil', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Salt', 'is_vegan' => true, 'is_vegetarian' => true], ['name' => 'Pepper', 'is_vegan' => true, 'is_vegetarian' => true]], [['name' => 'Vegetarian'], ['name' => 'Korean']]);
    }
}
